In [25]:
import numpy as np

In [50]:
which = 1
whichs = str(which)
infile="/home/craig/programs/rtlstm/test_kickz/densities/rho_"+whichs+".npy"
d = np.load(infile)
s=np.load("/home/craig/programs/rtlstm/test_kickz/densities/density_series.npy",allow_pickle=True).item()
p =np.load("/home/craig/programs/rtlstm/test_kickz/predicted_dynamics.npy")

In [ ]:
print(d.real)
print(s['density'][which][0].real)
d.real-s['density'][which][0].real

[[0.1156959  0.10661065 0.11563289 0.10536944]
 [0.10661065 0.09830489 0.10649873 0.09697993]
 [0.11563289 0.10649873 0.11561383 0.10540596]
 [0.10536944 0.09697993 0.10540596 0.09616544]]
[[0.1156959  0.10661065 0.11563289 0.10536944]
 [0.10661065 0.09830489 0.10649873 0.09697993]
 [0.11563289 0.10649873 0.11561383 0.10540596]
 [0.10536944 0.09697993 0.10540596 0.09616544]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
print(p.real[which])

[[[0.11351537 0.10249693 0.11561217 0.10748786]
  [0.10249693 0.09254923 0.10438268 0.09704635]
  [0.11561217 0.10438268 0.11779339 0.10952275]
  [0.10748786 0.09704635 0.10952275 0.10183387]]

 [[0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]]]


In [20]:
isReal = True

In [21]:
a = 10 if isReal else 20
a

10